=head1 This Week on perl5-porters (19-25 April 2004)

=head2 New compiler

Yves Orton tells the crowd about the newly released command-line compiler
by Microsoft, available from a free download. Follows some remarks on how
to build perl on Windows with it, and what are the odds and ends of the
differents versions of Microsoft's compilers.

    http://groups.google.com/groups?selm=71B318898201D311845C0008C75DAD1C0A44CD19%40defra1ex2


=head2 About this summary

This summary was written by Rafael Garcia-Suarez. Weekly summaries are
published on F<http://use.perl.org/> and posted on a mailing list, which
subscription address is F<perl5-summary-subscribe@perl.org>. Comments and
corrections welcome.
