=head1 TITLE

This Is The Last Major Revision

=head1 VERSION

  Maintainer: David Nicol <perl6rfc@davidnicol.com>
  Date: 5 Sep 2000
  Mailing List: perl6-meta@perl.org
  Number: 141
  Version: 2
  Status: Frozen

=head1 ABSTRACT

Future perl version numbers will converge on 2 * PI

=head1 DESCRIPTION

By the end of this committee meeting, we will have a language
that is arbitrarily extensible in accordance with decades of
computer programming practice.

Perl6 is NOT a quick hack done to save implementor time.  It is a
carefully crafted piece of fine work.  It is correct.

Having put all this work into it, we would like to see this
version stick around a while, in the way of Knuth's TeX language
or [pick your favorite historical math figure]'s [particular
lasting contribution.]

=head1 IMPLEMENTATION

Since versioning is a meta-implementation issue, all that
is required is that
we all agree that stealing TeX's versioning system is a good idea.

The first release will be 6, and then each subsequent
release may or may not extend a digit.

=head1 REFERENCES

TeX FAQ

