=head1 TITLE

Tweak POD's CE<lt>E<gt> 

=head1 VERSION

  Maintainer: Simon Cozens <simon@brecon.co.uk>
  Date: 24 Sep 2000
  Mailing List: perl6-language@perl.org
  Number: 280
  Version: 1
  Status: Developing

=head1 ABSTRACT

CE<lt>E<gt> is not as intuitive as it could be.

=head1 DESCRIPTION

In Perl 5.6.0, we altered the behaviour of the CE<lt>E<gt> construct in
POD, so that you could say C<CE<lt>E<lt> ... E<gt>E<gt>> to avoid the
problem that

    C<< $foo->bar >>

would be ended by the arrow. 

However, this isn't too Perlish, and there's an easier solution; give
the CE<lt>E<gt> the same semantics as a single quoted string with
C<q//>. That is:

=over 1

=item *

Do away with the need to escape stuff inside CE<lt>E<gt>, because that
stops you cutting and pasting the code.

=item *

Allow the use of alternate delimiters to avoid the arrow problem.

    C<$xyz>
    C/$foo->bar/

=back

=head1 IMPLEMENTATION

Just some tweaks to C<POD::Parser>, haha.

=head1 REFERENCES

None.
