=head1 TITLE

C<$^C> should be true when compiling 

=head1 VERSION

  Maintainer: Simon Cozens <simon@brecon.co.uk>
  Date: 25 Sep 2000
  Mailing List: perl6-language@perl.org
  Number: 305
  Version: 1
  Status: Developing

=head1 ABSTRACT

C<$^C> should be true when compiling, not just when the C<-c> flag is
set.


=head1 DESCRIPTION

The idea of C<$^C> is that it allows programs to change their behaviour
when being compiled. However, the way it's implemented means it's only
true when the C<-c> flag is given on the Perl command line. At the
moment, there's no way of telling whether you're in a C<BEGIN> block or
not, and there ought to be.

=head1 IMPLEMENTATION

Make C<$^C> true while the interpreter is compiling code, and not just
when it's going to compile and quit.

=head1 REFERENCES

None.
