=head1 TITLE

Eliminate bareword filehandles.

=head1 VERSION

  Maintainer: Peter Scott <peter@psdt.com>
  Date: 4 Aug 2000
  Last Modified: 29 Aug 2000
  Mailing List: perl6-language@perl.org
  Number: 33
  Version: 2
  Status: Frozen

=head1 ABSTRACT

Now that scalars (objects) can be used for filehandles, the bareword form
should be eliminated.

=head1 DESCRIPTION

The venerable bareword form of the filehandle leads to code that is
unnecessarily abstruse given that they can now be stored in
scalars.  Bareword filehandles are not lexical, and require the use of
typeglobs and C<local> to pass them to subroutines, concepts unnecessarily
advanced for such a beginner-type operation.

=head1 IMPLEMENTATION

Easy, hopefully.

=head1 REFERENCES

L<perlvar/"Typeglobs and Filehandles">
