=head1 TITLE
   
Request For New Pragma: Implicit
 
=head1 VERSION

  Maintainer: Bryan C. Warnock <bwarnock@gtemail.net>
  Date: 9 Aug 2000
  Mailing List: perl6-language@perl.org
  Number: 41
  Version: 2
  Status: Retired
  Replaced-By: 2

=head1 RETIRED
 
As of 9 Aug 2000, this RFC has been replaced by RFC 2.

