=head1 TITLE

Eliminate the optional C<sub> for C<BEGIN> etc block declarations

=head1 VERSION

  Maintainer: Peter Scott <peter@psdt.com>
  Date: 8 Aug 2000
  Last Modified: 29 Aug 2000
  Mailing List: perl6-language@perl.org
  Number: 68
  Version: 2
  Status: Frozen

=head1 ABSTRACT

The C<sub> keyword is currently optional on C<BEGIN>, C<END>, C<CHECK>,
C<INIT>.  Almost certainly no-one ever uses it.  It should be eliminated
as an option.

=head1 DESCRIPTION

C<BEGIN> etc have special semantics making them different from ordinary
subroutines; telling the user that they can use the C<sub> keyword gives
a false impression.

=head1 IMPLEMENTATION

Obvious.

=head1 REFERENCES

L<perlmod/"Package Constructors and Destructors">
