#!/bin/sh
#
# Start a pre-built docker container. /usr/bin/run is 'container-run.sh' script from docker.
#
IMAGE=${IMAGE:-quay.io/perl/perlweb:latest}
docker run --rm -P -p 8235:8235 -t -i -v `pwd`:/git/perlweb $IMAGE  /usr/bin/run
