#!/usr/bin/perl

use strict;
use warnings;
use CGI qw( :standard );

my $tier = 0;
my $n = 0;
my @rows;

my %tier_comment = (
    1 => "Top 10",
    2 => "Biggies",
    3 => "Not as big, but still important",
);

while (<DATA>) {
    chomp;
    
    if ( /^$/ ) {
	++$tier;
	push( @rows, Tr( td( {class=>"banner", colspan=>3}, "Tier #$tier: ", span( {class=>"title"}, $tier_comment{$tier} ) ) ) );
	next;
    }
    my ($dist,$author) = split;
    ++$n;

    push( @rows,
	Tr(
	    td( $dist ),
	    td( a( { href => "http://search.cpan.org/author/$author" } ), $author ),
	    td( join( " | ",
		a( { href => "http://search.cpan.org/dist/$dist" }, "Docs" ),
		a( { href => "http://rt.cpan.org/NoAuth/Bugs.html?Dist=$dist" }, "Bugs" ),
		a( { href => "http://testers.cpan.org/show/$dist.html" }, "Testers" ),
	   	a( { href => "http://cpanratings.perl.org/d/$dist" }, "Ratings" ),
	    ) ),
	)
    );
}

@rows = map { "$_\n" } @rows;
print table( {border=>0, cellspacing=>0, cellpadding=>5}, @rows );

__DATA__

CPANPLUS                 KANE
Compress-Zlib            PMQS
DBD-mysql                JWIED
DBI                      TIMB
HTML-Parser              GAAS
libwin32                 GSAR
libwww-perl              GAAS
MailTools                MARKOV
MIME-Base64              GAAS
URI                      GAAS

Date-Calc                STBEY
DBD-Oracle               TIMB
Digest-HMAC              GAAS
Digest-SHA1              GAAS
GD                       LDS
HTML-Tagset              SBURKE
IO-Socket-SSL            BEHROOZI
IO-stringy               ERYQ
Mail-SpamAssassin        JMASON
MIME-Lite                YVES
MIME-tools               ERYQ
Net-DNS                  CREIN
Net-Telnet               JROGERS
Net_SSLeay.pm            SAMPO
Parse-RecDescent         DCONWAY
Spreadsheet-WriteExcel   JMCNAMARA
Template-Toolkit         ABW
Term-ReadLine-Perl       ILYAZ
XML-Parser               COOPERCL
XML-Simple               GRANTM

Apache-DBI               ABH
Apache-Session           JBAKER
AppConfig                ABW
Archive-Tar              KANE
Archive-Zip              NEDKONZ
bioperl                  BIRNEY
Bit-Vector               STBEY
Cache-Cache              DCLINTON
CGI-Application          JERLBAUM
CGI-Kwiki                INGY
CGI-Session              SHERZODR
Class-DBI		 TMTM
Class-Date		 DLUX
Config-IniFiles          WADG
Convert-ASN1             GBARR
Crypt-Blowfish           DPARIS
Crypt-CBC                LDS
Crypt-DES                DPARIS
Crypt-SSLeay             CHAMAS
Data-ShowTable           AKSTE
DateManip                SBECK
DBD-CSV                  JZUCKER
DBD-ODBC                 JURL
DBD-Pg                   MERGL
DBIx-SearchBuilder       JESSE
Error                    UARUN
Expect                   RGIERSIG
GDGraph                  MVERB
GDTextUtil               MVERB
HTML-Mason               DROLSKY
HTML-Template            SAMTREGAR
HTML-Tree                SBURKE
Image-Info               GAAS
Image-Size               RJRAY
Inline                   INGY
IO-Tty                   RGIERSIG
libapreq                 JOESUF
libxml-perl              KMACLEOD
Mac-Carbon               CNANDOR
Mac-Glue                 CNANDOR
Mail-Box                 MARKOV
Mail-Sendmail            MIVKOVIC
MD5                      GAAS
Module-Build             KWILLIAMS
MP3-Info                 CNANDOR
Msql-Mysql-modules       JWIED
Net-Daemon               JWIED
Net-SNMP                 DTOWN
Net-SSH-Perl             BTROTT
PAR                      AUTRIJUS
Params-Validate          DROLSKY
PDF-API2                 AREIBENS
PDL                      KGB
perl-ldap                GBARR
PerlMagick               JCRISTY
Pod-Simple		 SBURKE
POE                      RCAPUTO
Regexp-Common            ABIGAIL
Scalar-List-Utils        GBARR
SOAP-Lite                KULCHENKO
SPOPS                    CWINTERS
Spreadsheet-ParseExcel   KWITKNR
TermReadKey              KJALB
Test-Reporter		 FOX
Text-CSV_XS              JWIED
Text-Iconv               MPIOTR
Text-Template		 MJD
Time-modules             MUIR
TimeDate                 RSE
WWW-Mechanize            PETDANCE
XML-DOM                  TJMATHER
XML-LibXML               PHISH
XML-SAX                  MSERGEANT
XML-Writer               DMEGG
XML-XPath                MSERGEANT
YAML                     INGY
