=head1 TITLE

The Phalanx Roster

=over 4

=item * Shawn Carroll

L<http://use.perl.org/~SparkeyG/>

=item * Nick Dronen

L<http://technolalia.com>

=item * Jason Gessner

L<http://multiply.org>

=item * Michael Graham

L<http://occamstoothbrush.com>

Gave a lightning talk for the Toronto Perl Mongers: L<http://occamstoothbrush.com/perl/talks/phalanx_talk/slides/>

=item * David Hand

L<http://davidhand.com/>

=item * Andy Lester

L<http://petdance.com/>

=item * Dominic Letarte

Somewhere in Canada

=item * Andrew Potozniak

L<http://www.potozniak.org>

=item * Andrew Savige

=item * Gabor Szabo

L<http://pti.col.il/>

L<http://debugger.perl.org/>

=item * Iain Truskett

L<http://iain.truskett.id.au>

=back
