=head1 TITLE 

Module Status

=head2 Date-Calc

Started with N tests.

Shawn Carroll has started on the tests for Date::Calc.

=head2 Regexp::Common

Started with 157,744 tests.

David Hand has his sights set on Regexp::Common, and is starting to work
with Abigail.

=head2 IO::Socket::SSL

Nick Dronen is starting.  v0.95 with 53 tests.

=head2 Test::Reporter

Andy Lester is working with Adam Foxson on preliminary ideas for Test::Reporter.

Version 1.20 has 54 tests.

=head2 XML::Simple

Jason Gessner is looking into doing XML::Simple.
