=head1 Human infrastructure

=over 4

=item *

Set up some sort of bug tracking system

=item *

Track metrics

=back

=head1 Test::Harness improvements

=over 4

=item *

Document the protocol

=item *

Add random run orders for tests

=item *

Add stats

=back

=head1 Stats

Need to keep track of what the improvements to the distros are.
If we add tests, we need to track that.

=head1 CPAN feedback process

=item *

Contacting the author

=item *

Developing tests

=item *

Bugs in existing RT tracking

=back

=head1 Perl feedback process

Work with the pumpking to define how patches should be fed back
