=head1 Grants Committee Charter

=head3 1. Purpose

The Grants Committee shall manage all Yet Another Society operations
related to grants issued under The Perl Foundation.  It shall be
granted all powers granted to the Board of Directors relevant to these
operations except:

=over

=item 1

Those that are specifically denied under the Yet Another Society Bylaws.

=item 2

The sale or purchase of assets worth greater than $500.

=item 3

Borrowing money or assuming any long term liabilities.

=item 4

Entering into any contract or agreement worth more than $10,000.

=back

The Committee shall be restricted to only those activities that are
consistent with Yet Another Society's tax exempt status.

=head3 2. Objectives

The Committee shall support the following specific tasks:

=over

=item 1

Grant Allocation

=item 2

Grant Management

=back

The Board of Directors may add or remove tasks from time to time.

=head3 3. Membership

The Committee shall consist of at least one and at most eleven
members.  The Board of Directors shall always have at least one
representative on the committee.  The Committee shall ensure adequate
membership to carry out the tasks specified in Section 2.

The initial membership of the Committee shall be appointed by the
Board of Directors. Members shall serve for 1 year terms.  There shall
be no limit to the number of terms any member may serve.

Members of the Committee shall be nominated by the Committee. New
members shall be elected by a majority vote of the Committee. Any
member can be removed by a majority vote of the Committee. At any
time, a member can be added, removed, or replaced by the Board of
Directors. In the event of the death, resignation, or removal of a
member, the Committee shall elect a new member.

=head3 4. Meetings & Reports

The members of the Committee must meet at least once per year.  Due to
the international nature of the Committee, these meetings will be held
via email. It shall provide a report of all recent operations at least
once every three months.

=head3 5. Duration

The Committee shall serve until dissolved by the board of directors.


