package Develooper::TemplateFiller;
use strict;
use lib "$ENV{CBROOT}/lib";
use Text::Template;   
use Exporter;
use vars qw(@EXPORT @ISA);
@ISA = qw(Exporter);
@EXPORT = qw(template_filler);

use Combust::Config;

sub template_filler {
  my %p = @_;
  my $template = new Text::Template (%{$p{new}})
    or die "Couldn't make template: $Text::Template::ERROR; aborting";

  $p{hash} ||= {};
  $p{hash}->{dont_edit} = <<EOT;
# ========================================================================
# THIS FILE IS AUTOGENERATED.  DO NOT EDIT.  YOUR CHANGES WILL GO BYE BYE!
# ========================================================================
EOT

  $template->fill_in(OUTPUT  => \*STDOUT,
                     PACKAGE => "T", 
                     HASH    => { 
                                 $p{hash} ? %{$p{hash}} : ()
                                },
                     $p{fill_in} ? %{$p{fill_in}} : ()
                    );
}


1;
