=head1 perlfoundation.org to-do list

=head2 Project list

Ongoing status of what is going on out in Perl land

=head2 Fixing the RSS feed

It looks like the RSS feed doesn't quote all its entities properly.

=head2 Perlfoundation navigation

We need to improve the sidebar navigation to be less busy and more
functional.

=head2 donate site

It looks like the donation site isn't currently housed in the svn
repository, need to get that taken care of and update it to match
the rest of perlfoundation.org