=head1 Who's Who at The Perl Foundation

=head3 Board of Directors:

=over

=item * Chairman - Kevin Lenzo

=item * Secretary - Nathan Torkington

=item * President - Allison Randal

=item * Vice President/Treasurer - Kurt DeMaagd

=back
                                                                                                           
=head3 Steering Committee:

=over

=item * Steering Committee Chair - Lisa Wolfisch

=item * Grants - Dan Sugalski

=item * Perl.org - Ask Bjorn Hansen and Robert Spier

=item * PerlFoundation.org - Kevin Meltzer

=item * Conferences - Jeff Bisbee

=item * Public Relations - Gavin Estey

=item * Donor Relations - Larry Hixson

=item * Perl Mongers - Dave Cross

=item * CPAN - Elaine Ashton

=item * "At Large" committee members:

=over

=item * Adam Turoff (Awards)

=item * Uri Guttman (Social Events)

=item * Brian Ingerson (Outreach)

=back

=item * Ex officio:

=over

=item * Nathan Torkingon (Secretary)

=item * Allison Randal (President)

=item * Kurt DeMaagd (Treasurer)

=back

=back

=head3 Grants Committee:

=over

=item * Grants Chair - Dan Sugalski and Hugo van der Sanden co-chair

=item * Stas Bekman

=item * Leon Brocard

=item * Nicholas Clark

=item * Rafael Garcia-Suarez

=item * Brigitte Jellinek

=item * Grant Managers (non-voting):

=over

=item * Baden Hughes

=item * Curtis Poe

=item * Mark Senn

=item * Martin Streicher

=back

=item * Ex officio:

=over 

=item * Allison Randal (President) as board liason

=back

=head3  Conferences Committee:

=over

=item * Conferences Chair - Jeff Bisbee

=item * Kevin Meltzer

=item * Uri Guttman

=back
