#!/usr/bin/perl

use strict;
use warnings;
use CGI qw( :standard );

my $tier = "";
my @rows;

while ( <> ) {
    chomp;
    next unless /./;

    if ( /^=head1 (.+)/ ) {
        $tier = $1;
        push( @rows, Tr( td( {class=>"banner", colspan=>3}, h3( $tier ) ) ) );
        next;
    }
    my ($dist,$author) = split;

    push( @rows,
        Tr(
            td( $dist ),
            td( a( { href => "http://search.cpan.org/~$author" } ), $author ),
            td( join( "\n|\n",
                a( { href => "http://search.cpan.org/dist/$dist" }, "Docs" ),
                a( { href => "http://rt.cpan.org/NoAuth/Bugs.html?Dist=$dist" }, "Bugs" ),
                a( { href => "http://testers.cpan.org/show/$dist.html" }, "Testers" ),
                a( { href => "http://cpanratings.perl.org/d/$dist" }, "Ratings" ),
            ) ),
        )
    );
}

@rows = map { "$_\n" } @rows;
print table( {class=>'phalanx_table'}, @rows );
