=head1 Special testing squad

Test-Builder-Tester  MARKF
Test-Exception  ADIE
Test-Harness  PETDANCE
Test-NoWarnings  FDALY
Test-Pod  PETDANCE
Test-Pod-Coverage  PETDANCE
Test-Reporter  FOX
Test-Simple  MSCHWERN
Test-Warn  BIGJ

=head1 The Top 10

CPANPLUS  KANE
DBD-mysql  RUDY
DBI  TIMB
GD  LDS
HTML-Parser  GAAS
libwww-perl  GAAS
MIME-Base64  GAAS
Net_SSLeay.pm  SAMPO
perl-ldap  GBARR
XML-Parser  MSERGEANT

=head1 The Next 20

Apache-ASP  CHAMAS
Archive-Tar  KANE
Archive-Zip  NEDKONZ
CGI.pm  LDS
Compress-Zlib  PMQS
DateManip  SBECK
DBD-Oracle  TIMB
DBD-Pg  RUDY
DB_File  PMQS
Digest  GAAS
Digest-SHA1  GAAS
Digest-HMAC  GAAS
Digest-MD5  GAAS
HTML-Tagset  SBURKE
HTML-Template  SAMTREGAR
libnet  GBARR
MailTools  MARKOV
MIME-tools  ERYQ
Net-DNS  CREIN
PathTools  KWILLIAMS
Time-HiRes  JHI
URI  GAAS

=head1 The Rest of the 100

Apache-DBI  ABH
Apache-Session  JBAKER
Apache-Test  GOZER
AppConfig  ABW
App-Info  DWHEELER
Authen-PAM  NIKIP
Authen-SASL  GBARR
BerkeleyDB  PMQS
Bit-Vector  STBEY
Carp-Clan  STBEY
Chart  CHARTGRP
Class-Accessor  KASEI
Class-Data-Inheritable  MSCHWERN
Class-DBI  TMTM
Class-Singleton  ABW
Class-Trigger  MIYAGAWA
Compress-Zlib-Perl  NWCLARK
Config-IniFiles  WADG
Convert-ASN1  GBARR
Convert-TNEF  DOUGW
Convert-UUlib  MLEHMANN
CPAN  ANDK
Crypt-CBC  LDS
Crypt-DES  DPARIS
Crypt-SSLeay  CHAMAS
Data-Dumper  ILYAM
Date-Calc  STBEY
DateTime  DROLSKY
DBD-DB2  IBMTORDB2
DBD-ODBC  JURL
DBD-SQLite  MSERGEANT
DBD-Sybase  MEWP
Device-SerialPort  COOK
Digest-SHA  MSHELOR
Encode  DANKOGAI
Event  JPRIT
Excel-Template  RKINYON
Expect  RGIERSIG
ExtUtils-MakeMaker  MSCHWERN
File-Scan  HDIAS
File-Tail  MGRABNAR
File-Temp  TJENNESS
GDGraph  MVERB
GDTextUtil  MVERB
Getopt-Long  JV
HTML-Mason  DROLSKY
Ima-DBI  TMTM
Image-Size  RJRAY
Inline  INGY
IO  GBARR
IO-All  INGY
IO-Socket-SSL  BEHROOZI
IO-String  GAAS
IO-stringy  ERYQ
IO-Zlib  TOMHUGHES
IPC-Run  RBS
libxml-perl  KMACLEOD
Mail-Audit  SIMON
Mail-ClamAV  SABECK
Mail-Sendmail  MIVKOVIC
Math-Pari  ILYAZ
MIME-Lite  ERYQ
mod_perl  GOZER
Module-Build  KWILLIAMS
MP3-Info  CNANDOR
Net-Daemon  JWIED
Net-FTP-Common  TBONE
Net-Ping  BBB
Net-Server  RHANDOM
Net-SNMP  DTOWN
Net-SSH-Perl  DROLSKY
Net-Telnet  JROGERS
OLE-Storage_Lite  JMCNAMARA
Params-Validate  DROLSKY
Parse-RecDescent  DCONWAY
PerlMagick  JCRISTY
PlRPC  JWIED
PodParser  MAREKR
POE  RCAPUTO
SNMP  GSM
SOAP-Lite  SOAP
Spreadsheet-ParseExcel  KWITKNR
Spreadsheet-WriteExcel  JMCNAMARA
Spreadsheet-WriteExcelXML  JMCNAMARA
Storable  AMS
Template-Toolkit  ABW
TermReadKey  JSTOWE
Term-ReadLine-Perl  ILYAZ
Text-Iconv  MPIOTR
TimeDate  GBARR
Time-modules  MUIR
Unicode-String  GAAS
UNIVERSAL-moniker  KASEI
Unix-Syslog  MHARNISCH
WWW-Mechanize  PETDANCE
XML-DOM  TJMATHER
XML-Generator  BHOLZMAN
XML-LibXML  PHISH
XML-NamespaceSupport  RBERJON
XML-SAX  MSERGEANT
XML-Simple  GRANTM
XML-Writer  JOSEPHW
YAML  INGY
