#!/bin/bash
exec </dev/null
exec 2>&1

find .nospin.start -mmin -1 -exec echo "*** rate limiting restart ***" \; -exec sleep 3 \;
touch .nospin.start

echo Starting

# some rough assumptions here
cd ../../..

if [ -z $CBROOT ]; then
  export CBROOTLOCAL=`pwd`
  export CBROOT=$CBROOTLOCAL/combust
fi

exec ./combust/bin/httpd


